### ISSUE TITLE
Incorrect dependency

### ISSUE THREAD

**Issue by MoritzMaxeiner** [tarsius/llama#1]
Hi, thank you for the package. Here:

https://github.com/tarsius/llama/blob/d98debc6ca4c7cc86e9dd944b2393698802ef077/llama.el#L10

you define a dependency on `(("emacs" "26.1"))`, but it should be `((emacs "26.1")) `. When I just attempted to `package-install` epkg, which pulls in llama as a dependency, it fails with the following stack head:

```
Debugger entered--Lisp error: (error "Package ‘emacs’ (version 26.1) is unavailable")
  signal(error ("Package ‘emacs’ (version 26.1) is unavailable"))
  error("Package `emacs' (version 26.1) is unavailable")
```

**Comment by tarsius** [comment]
Thanks!
